### ISSUE TITLE
How to set application icon in .net

### ISSUE THREAD

**Issue by 542353921** [qmlnet/qmlnet#159]
hi,
How to set application icon like this

int main(int argc, char *argv[])
{
    QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
    QGuiApplication app(argc, argv);
    app.setWindowIcon(QIcon(":/favicon.ico"));

    QQmlApplicationEngine engine;
    engine.load(QUrl(QLatin1String("qrc:/main.qml")));

    return app.exec();
}

thanks

**Comment by MosiQt** [comment]
I had similar issue and solved it by writing my  own plugin by overwriting QQuickWindow. I've used the plugin instead of ApplicationWindow in qml.  In the plugin class, you can easily set the windowIcon. 
![1](https://user-images.githubusercontent.com/53909162/65223095-a7d2a580-dad5-11e9-8330-40fe278a31f4.png)

After that you can set the icon path in qml:
![2](https://user-images.githubusercontent.com/53909162/65223188-dea8bb80-dad5-11e9-845f-2fdac0c94f27.png)

**Comment by nyashabryan** [comment]
@MosiQt do you mind going in a bit more detail about the process? Newbie here.

**Comment by vadi2** [comment]
An upcoming version of QML.net will have `app.SetWindowIcon(png path)` method that makes this simpler.
