### ISSUE TITLE
App using native hosting crashes immediately

### ISSUE THREAD

**Issue by BrianAllred** [qmlnet/qmlnet#178]
I've set up native hosting like the documentation specifies (only difference is I moved TestObject to its own file within the namespace). When I run, I get the error below.

```
Unhandled exception. System.Exception: Args is invalid, must contain three entries which are pointers to native types.
   at Qml.Net.Host.Run(String[] args, Func`5 action)
   at QmlYodel.Program.Main(String[] _) in /home/brian/Documents/QmlYodel/net/Program.cs:line 16
18:14:37: The program has unexpectedly finished.
```

Line 16 is the `return Host.Run(...` line.

**Comment by pauldotknopf** [comment]
I suspect you are using the native from git, while using the .NET lib from NuGet. The native/net libs must be aligned.

I recommend adding "QmlNet" as a submodule. Compile in the native bits (including the .pri file), and refernce the Qml.Net.csproj project directly from the submodule (instead of from Nuget).

**Comment by BrianAllred** [comment]
Your suspicion was correct, thanks!
