### ISSUE TITLE
Support for .NET DateTime type in Qml.

### ISSUE THREAD

**Issue by MaxMommersteeg** [qmlnet/qmlnet#99]
Now I have to convert it to string using a helper function on another .NET type: https://github.com/MaxMommersteeg/Qml.Net.Chat/blob/master/src/Qml.Net.Chat.Client/Controllers/ChatController.cs#L66

Can we build native support for this type, do I have to register the DateTime type or can we make this possible with the [Date Qml type]   (http://doc.qt.io/qt-5/qml-qtqml-date.html)?

**Comment by pauldotknopf** [comment]
In .NET, ```System.DateTime``` is horrible. Mainly because it doesn't contain the actual UTC offset. That means a date time value with ```LocalKind``` could literally be any time.

Because of this, ```System.DateTime``` doesn't translate well to other languages due to the missing precision.

Instead, use ```System.DateTimeOffset```. It get's represeted perfectly in .NET and JS as fully featured and native date types.

**Comment by pauldotknopf** [comment]
It gets automatically converted back-and-forth, it's a built-in supported data type in qmlnet.

Check the unit tests.

**Comment by MaxMommersteeg** [comment]
Ah check, found it here: https://github.com/qmlnet/qmlnet/blob/develop/src/net/Qml.Net.Tests/Qml/DateTimeOffsetTests.cs

Perhaps I can focus on writing down features based on unittests and add them to the Github.io pages later this week.

I will close this issue, thanks!
